/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.017, 0]}>
        <mesh geometry={nodes.pants002.geometry} material={materials['Material.012']} position={[0, 7.801, 0.015]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0, 7.801, 0.008]}>
          <mesh geometry={nodes.Cube005.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Hoodie001.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Jordans010.geometry} material={materials.Material} position={[-0.06, -7.448, -0.913]} scale={0.339} />
          <mesh geometry={nodes.Jordans011.geometry} material={materials['Material.004']} position={[-0.06, -7.448, -0.913]} scale={0.339} />
          <mesh geometry={nodes.Jordans012.geometry} material={materials['RED-JORDANS']} position={[-0.06, -7.448, -0.913]} scale={0.339} />
          <mesh geometry={nodes.Jordans013.geometry} material={materials.Material} position={[-0.045, -7.448, 0.895]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.339, 0.339, 0.339]} />
          <mesh geometry={nodes.Jordans014.geometry} material={materials['Material.004']} position={[-0.045, -7.448, 0.895]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.339, 0.339, 0.339]} />
          <mesh geometry={nodes.Jordans015.geometry} material={materials['RED-JORDANS']} position={[-0.045, -7.448, 0.895]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.339, 0.339, 0.339]} />
          <mesh geometry={nodes.pants001.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Text001.geometry} material={materials.NIKE} position={[0.699, -1.715, -0.276]} rotation={[1.503, 0, -1.71]} scale={0.073} />
        </mesh>
      </group>
      <directionalLight intensity={4} decay={2} position={[27.127, 6.914, -0.368]} />
      <directionalLight intensity={4} decay={2} position={[-19.859, 10, 0.594]} />
      <pointLight intensity={40} decay={2} position={[1.803, 0.3, 0.23]} />
      <PerspectiveCamera makeDefault={false} position={[6.96, 9.714, 5.127]} rotation={[-0.808, 0.821, 0.654]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
