/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 scene.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera} from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials} = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Room10gltf">
          <group name="akko_pct" position={[-0.292, 1.631, -2.443]} rotation={[1.561, 0, 0.337]} scale={0.068} />
          <group name="box04" position={[0.439, 1.837, -2.691]} rotation={[0, -0.327, 0]}>
            <mesh name="Cube247" geometry={nodes.Cube247.geometry} material={materials['Raindrops On The Glass']} />
            <mesh name="Cube247_1" geometry={nodes.Cube247_1.geometry} material={materials['Green marble']} />
          </group>
          <group name="box02" position={[0.595, 1.759, -2.406]} rotation={[Math.PI / 2, 0, 0.157]} scale={[0.047, 0.024, 0.047]}>
            <mesh name="meshId1_name001" geometry={nodes.meshId1_name001.geometry} material={materials['White calacatta marble']} />
            <mesh name="meshId1_name001_1" geometry={nodes.meshId1_name001_1.geometry} material={materials['White Stone']} />
          </group>
          <group name="printer" position={[2.009, 1.224, -2.173]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.012}>
            <mesh name="Cube221" geometry={nodes.Cube221.geometry} material={materials['Carbon Fibre']} />
            <mesh name="Cube221_1" geometry={nodes.Cube221_1.geometry} material={materials['Rubber Black']} />
          </group>
          <group name="monitor_mount" position={[-1.081, -0.478, 0.175]} scale={1.544}>
            <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Black Iron']} />
            <lineSegments name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials['Black Iron']} />
          </group>
          <group name="keyboard" position={[1.665, 0.838, -0.683]} rotation={[0, -Math.PI / 2, 0]} scale={0.055}>
            <mesh name="meshId1_name" geometry={nodes.meshId1_name.geometry} material={materials['White Marble']} />
            <mesh name="meshId1_name_1" geometry={nodes.meshId1_name_1.geometry} material={materials['Keyboard Layout ']} />
          </group>
          <group name="Text064" position={[2.135, 0.886, 0.553]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.098}>
            <mesh name="Text061" geometry={nodes.Text061.geometry} material={materials['Material.036']} />
            <mesh name="Text061_1" geometry={nodes.Text061_1.geometry} material={materials['5264980.001']} />
            <mesh name="Text061_2" geometry={nodes.Text061_2.geometry} material={materials['ВЕНТИЛЯТОР.001']} />
            <mesh name="Text061_3" geometry={nodes.Text061_3.geometry} material={materials['3672357896.001']} />
            <mesh name="Text061_4" geometry={nodes.Text061_4.geometry} material={materials['476823.001']} />
            <mesh name="Text061_5" geometry={nodes.Text061_5.geometry} material={materials[',kz.002']} />
            <mesh name="Text061_6" geometry={nodes.Text061_6.geometry} material={materials['26345.001']} />
            <mesh name="Text061_7" geometry={nodes.Text061_7.geometry} material={materials['78969.001']} />
            <mesh name="Text061_8" geometry={nodes.Text061_8.geometry} material={materials['5643.001']} />
            <mesh name="Text061_9" geometry={nodes.Text061_9.geometry} material={materials[',kz.003']} />
            <mesh name="Text061_10" geometry={nodes.Text061_10.geometry} material={materials['NZXT.001']} />
            <mesh name="Text061_11" geometry={nodes.Text061_11.geometry} material={materials['2345267.001']} />
            <mesh name="Text061_12" geometry={nodes.Text061_12.geometry} material={materials['Material.018']} />
            <mesh name="Text061_13" geometry={nodes.Text061_13.geometry} material={materials['Material.020']} />
            <mesh name="Text061_14" geometry={nodes.Text061_14.geometry} material={materials['345.004']} />
            <mesh name="Text061_15" geometry={nodes.Text061_15.geometry} material={materials['Material.025']} />
            <mesh name="Text061_16" geometry={nodes.Text061_16.geometry} material={materials['5654.001']} />
            <mesh name="Text061_17" geometry={nodes.Text061_17.geometry} material={materials['768.001']} />
            <mesh name="Text061_18" geometry={nodes.Text061_18.geometry} material={materials['625341234.001']} />
            <mesh name="Text061_19" geometry={nodes.Text061_19.geometry} material={materials['1234.001']} />
            <mesh name="Text061_20" geometry={nodes.Text061_20.geometry} material={materials['Material.026']} />
            <mesh name="Text061_21" geometry={nodes.Text061_21.geometry} material={materials['3.001']} />
            <mesh name="Text061_22" geometry={nodes.Text061_22.geometry} material={materials['23546.001']} />
            <mesh name="Text061_23" geometry={nodes.Text061_23.geometry} material={materials['56234.001']} />
            <mesh name="Text061_24" geometry={nodes.Text061_24.geometry} material={materials['4352.001']} />
            <mesh name="Text061_25" geometry={nodes.Text061_25.geometry} material={materials['456.001']} />
            <mesh name="Text061_26" geometry={nodes.Text061_26.geometry} material={materials['234573.001']} />
            <mesh name="Text061_27" geometry={nodes.Text061_27.geometry} material={materials['5.001']} />
            <mesh name="Text061_28" geometry={nodes.Text061_28.geometry} material={materials['4568.001']} />
            <mesh name="Text061_29" geometry={nodes.Text061_29.geometry} material={materials['5430.001']} />
            <mesh name="Text061_30" geometry={nodes.Text061_30.geometry} material={materials['45632.001']} />
            <mesh name="Text061_31" geometry={nodes.Text061_31.geometry} material={materials['78480.001']} />
            <mesh name="Text061_32" geometry={nodes.Text061_32.geometry} material={materials['7894.001']} />
            <mesh name="Text061_33" geometry={nodes.Text061_33.geometry} material={materials['64595.001']} />
            <mesh name="Text061_34" geometry={nodes.Text061_34.geometry} material={materials['345895.001']} />
            <mesh name="Text061_35" geometry={nodes.Text061_35.geometry} material={materials['3764487.001']} />
            <mesh name="Text061_36" geometry={nodes.Text061_36.geometry} material={materials['Material.027']} />
            <mesh name="Text061_37" geometry={nodes.Text061_37.geometry} material={materials['Material.028']} />
            <mesh name="Text061_38" geometry={nodes.Text061_38.geometry} material={materials.ВЕНЕТ_БОК} />
            <mesh name="Text061_39" geometry={nodes.Text061_39.geometry} material={materials['ВЕНЕТ_БОК.001']} />
            <mesh name="Text061_40" geometry={nodes.Text061_40.geometry} material={materials['1234628.001']} />
            <mesh name="Text061_41" geometry={nodes.Text061_41.geometry} material={materials['Material.029']} />
            <mesh name="Text061_42" geometry={nodes.Text061_42.geometry} material={materials['234575.001']} />
            <mesh name="Text061_43" geometry={nodes.Text061_43.geometry} material={materials['2.003']} />
            <mesh name="Text061_44" geometry={nodes.Text061_44.geometry} material={materials['3245637.001']} />
            <mesh name="Text061_45" geometry={nodes.Text061_45.geometry} material={materials['23.001']} />
            <mesh name="Text061_46" geometry={nodes.Text061_46.geometry} material={materials['Material.030']} />
            <mesh name="Text061_47" geometry={nodes.Text061_47.geometry} material={materials['54737456.001']} />
            <mesh name="Text061_48" geometry={nodes.Text061_48.geometry} material={materials['5436487.001']} />
            <mesh name="Text061_49" geometry={nodes.Text061_49.geometry} material={materials.Rog_Stroke} />
            <mesh name="Text061_50" geometry={nodes.Text061_50.geometry} material={materials['Corsair.004']} />
            <mesh name="Text061_51" geometry={nodes.Text061_51.geometry} material={materials['Corsair.005']} />
            <mesh name="Text061_52" geometry={nodes.Text061_52.geometry} material={materials['Corsair.006']} />
            <mesh name="Text061_53" geometry={nodes.Text061_53.geometry} material={materials['Corsair.007']} />
            <mesh name="Text061_54" geometry={nodes.Text061_54.geometry} material={materials['3567.001']} />
            <mesh name="Text061_55" geometry={nodes.Text061_55.geometry} material={materials['ЗОЛОТО_ЦЫГАН_.015']} />
            <mesh name="Text061_56" geometry={nodes.Text061_56.geometry} material={materials['Rog.001']} />
            <mesh name="Text061_57" geometry={nodes.Text061_57.geometry} material={materials['46578236.001']} />
            <mesh name="Text061_58" geometry={nodes.Text061_58.geometry} material={materials['Material.031']} />
            <mesh name="Text061_59" geometry={nodes.Text061_59.geometry} material={materials['1234512.001']} />
            <mesh name="Text061_60" geometry={nodes.Text061_60.geometry} material={materials['25634784.001']} />
            <mesh name="Text061_61" geometry={nodes.Text061_61.geometry} material={materials['23453795.001']} />
            <mesh name="Text061_62" geometry={nodes.Text061_62.geometry} material={materials['Material.032']} />
            <mesh name="Text061_63" geometry={nodes.Text061_63.geometry} material={materials['Material.033']} />
            <mesh name="Text061_64" geometry={nodes.Text061_64.geometry} material={materials['564334567.001']} />
            <mesh name="Text061_65" geometry={nodes.Text061_65.geometry} material={materials['6970876.001']} />
            <mesh name="Text061_66" geometry={nodes.Text061_66.geometry} material={materials['КОНДЕНСАТОР.001']} />
            <mesh name="Text061_67" geometry={nodes.Text061_67.geometry} material={materials['43576453.001']} />
            <mesh name="Text061_68" geometry={nodes.Text061_68.geometry} material={materials['45648.001']} />
            <mesh name="Text061_69" geometry={nodes.Text061_69.geometry} material={materials['254362.001']} />
            <mesh name="Text061_70" geometry={nodes.Text061_70.geometry} material={materials['23426.001']} />
            <mesh name="Text061_71" geometry={nodes.Text061_71.geometry} material={materials['324652.001']} />
            <mesh name="Text061_72" geometry={nodes.Text061_72.geometry} material={materials['3456.001']} />
            <mesh name="Text061_73" geometry={nodes.Text061_73.geometry} material={materials['3425.001']} />
            <mesh name="Text061_74" geometry={nodes.Text061_74.geometry} material={materials['65433.001']} />
            <mesh name="Text061_75" geometry={nodes.Text061_75.geometry} material={materials['456783.001']} />
            <mesh name="Text061_76" geometry={nodes.Text061_76.geometry} material={materials['967870-.001']} />
            <mesh name="Text061_77" geometry={nodes.Text061_77.geometry} material={materials['264524.001']} />
            <mesh name="Text061_78" geometry={nodes.Text061_78.geometry} material={materials['234964.001']} />
            <mesh name="Text061_79" geometry={nodes.Text061_79.geometry} material={materials['423526.001']} />
            <mesh name="Text061_80" geometry={nodes.Text061_80.geometry} material={materials['254638.001']} />
            <mesh name="Text061_81" geometry={nodes.Text061_81.geometry} material={materials['3465483.001']} />
            <mesh name="Text061_82" geometry={nodes.Text061_82.geometry} material={materials['38579.001']} />
            <mesh name="Text061_83" geometry={nodes.Text061_83.geometry} material={materials['65433564.001']} />
            <mesh name="Text061_84" geometry={nodes.Text061_84.geometry} material={materials.ЦИЛИНДР_ДИСПЛЕЙ} />
            <mesh name="Text061_85" geometry={nodes.Text061_85.geometry} material={materials.Burnt_Metal} />
            <mesh name="Text061_86" geometry={nodes.Text061_86.geometry} material={materials['Burnt_Metal.001']} />
            <mesh name="Text061_87" geometry={nodes.Text061_87.geometry} material={materials['34569453.001']} />
            <mesh name="Text061_88" geometry={nodes.Text061_88.geometry} material={materials['2546709-.001']} />
            <mesh name="Text061_89" geometry={nodes.Text061_89.geometry} material={materials['Material.034']} />
            <mesh name="Text061_90" geometry={nodes.Text061_90.geometry} material={materials['65423.001']} />
            <mesh name="Text061_91" geometry={nodes.Text061_91.geometry} material={materials['435273.001']} />
            <mesh name="Text061_92" geometry={nodes.Text061_92.geometry} material={materials['456721344.001']} />
            <mesh name="Text061_93" geometry={nodes.Text061_93.geometry} material={materials['2345784623.001']} />
            <mesh name="Text061_94" geometry={nodes.Text061_94.geometry} material={materials['354648.001']} />
            <mesh name="Text061_95" geometry={nodes.Text061_95.geometry} material={materials['63542.001']} />
            <mesh name="Text061_96" geometry={nodes.Text061_96.geometry} material={materials['4534595.002']} />
            <mesh name="Text061_97" geometry={nodes.Text061_97.geometry} material={materials['RAM_cAge.006']} />
            <mesh name="Text061_98" geometry={nodes.Text061_98.geometry} material={materials.RAM_moth} />
            <mesh name="Text061_99" geometry={nodes.Text061_99.geometry} material={materials['RAM_cAge.001']} />
            <mesh name="Text061_100" geometry={nodes.Text061_100.geometry} material={materials.RAM_Gols} />
            <mesh name="Text061_101" geometry={nodes.Text061_101.geometry} material={materials.RAM_cAge} />
            <mesh name="Text061_102" geometry={nodes.Text061_102.geometry} material={materials['5623265.001']} />
            <mesh name="Text061_103" geometry={nodes.Text061_103.geometry} material={materials['RAM_cAge.002']} />
            <mesh name="Text061_104" geometry={nodes.Text061_104.geometry} material={materials['RAM_Gols.001']} />
            <mesh name="Text061_105" geometry={nodes.Text061_105.geometry} material={materials['RAM_cAge.003']} />
            <mesh name="Text061_106" geometry={nodes.Text061_106.geometry} material={materials['RAM_moth.001']} />
            <mesh name="Text061_107" geometry={nodes.Text061_107.geometry} material={materials['RAM_moth.002']} />
            <mesh name="Text061_108" geometry={nodes.Text061_108.geometry} material={materials['RAM_cAge.005']} />
            <mesh name="Text061_109" geometry={nodes.Text061_109.geometry} material={materials['RAM_Gols.002']} />
            <mesh name="Text061_110" geometry={nodes.Text061_110.geometry} material={materials['RAM_cAge.004']} />
            <mesh name="Text061_111" geometry={nodes.Text061_111.geometry} material={materials['265442354.001']} />
            <mesh name="Text061_112" geometry={nodes.Text061_112.geometry} material={materials['5436.001']} />
            <mesh name="Text061_113" geometry={nodes.Text061_113.geometry} material={materials['RAM_Gols.003']} />
            <mesh name="Text061_114" geometry={nodes.Text061_114.geometry} material={materials['RAM_cAge.007']} />
            <mesh name="Text061_115" geometry={nodes.Text061_115.geometry} material={materials['RAM_moth.003']} />
            <mesh name="Text061_116" geometry={nodes.Text061_116.geometry} material={materials['453646798.001']} />
            <mesh name="Text061_117" geometry={nodes.Text061_117.geometry} material={materials['85678.001']} />
            <mesh name="Text061_118" geometry={nodes.Text061_118.geometry} material={materials['345698746.001']} />
            <mesh name="Text061_119" geometry={nodes.Text061_119.geometry} material={materials['Material.035']} />
            <mesh name="Text061_120" geometry={nodes.Text061_120.geometry} material={materials['34753.001']} />
            <mesh name="Text061_121" geometry={nodes.Text061_121.geometry} material={materials['ЗОЛОТО_ЦЫГАН_.016']} />
            <mesh name="Text061_122" geometry={nodes.Text061_122.geometry} material={materials['ЗОЛОТО_ЦЫГАН_.017']} />
            <mesh name="Text061_123" geometry={nodes.Text061_123.geometry} material={materials['ЗОЛОТО_ЦЫГАН_.018']} />
            <mesh name="Text061_124" geometry={nodes.Text061_124.geometry} material={materials['376893.001']} />
            <mesh name="Text061_125" geometry={nodes.Text061_125.geometry} material={materials['ЗОЛОТО_ЦЫГАН_.019']} />
            <mesh name="Text061_126" geometry={nodes.Text061_126.geometry} material={materials['3452065.001']} />
            <mesh name="Text061_127" geometry={nodes.Text061_127.geometry} material={materials.Rgb_Lights_RAM} />
            <mesh name="Text061_128" geometry={nodes.Text061_128.geometry} material={materials.Platinum_RGB} />
            <mesh name="Text061_129" geometry={nodes.Text061_129.geometry} material={materials['Platinum_RGB.001']} />
            <mesh name="Text061_130" geometry={nodes.Text061_130.geometry} material={materials['Platinum_RGB.002']} />
            <mesh name="Text061_131" geometry={nodes.Text061_131.geometry} material={materials['Platinum_RGB.003']} />
            <lineSegments name="Text061_132" geometry={nodes.Text061_132.geometry} material={materials['Material.036']} />
          </group>
          <group name="Cube" position={[0, -1.007, 0]}>
            <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Poured concrete']} />
            <lineSegments name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials['Poured concrete']} />
          </group>
          <PerspectiveCamera name="Camera001" makeDefault={true} far={1000} near={0.1} fov={22.895} position={[-6.949, 2.004, 4.145]} rotation={[-0.237, -0.987, -0.189]} />
          <pointLight name="Area" intensity={3} decay={2} color="#efe2c3" position={[0.231, 2, -0.573]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.631, 1.942, 0.51]} />
          <pointLight name="Area001" intensity={1} decay={2} color="#ff0011" position={[-0.411, 2.349, -2.353]} rotation={[-2.604, 0, 0]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area002" intensity={1} decay={2} color="#ff5d0d" position={[0.164, 2.365, -2.354]} rotation={[-2.604, 0, 0]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area003" intensity={1} decay={2} color="#ff0011" position={[0.752, 2.365, -2.364]} rotation={[-2.604, 0, 0]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area004" intensity={1} decay={2} color="#ff890e" position={[1.368, 2.365, -2.364]} rotation={[-2.604, 0, 0]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area005" intensity={1} decay={2} color="#ff400f" position={[1.983, 2.365, -2.383]} rotation={[-2.604, 0, 0]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area006" intensity={1} decay={2} color="#ff0011" position={[2.103, 2.307, -2.007]} rotation={[-1.279, 1.033, -Math.PI / 2]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area007" intensity={1} decay={2} color="#ff5200" position={[2.131, 2.106, -1.337]} rotation={[-1.279, 1.033, -Math.PI / 2]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area008" intensity={1} decay={2} color="#ff9b20" position={[2.15, 1.899, -0.649]} rotation={[-1.279, 1.033, -Math.PI / 2]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area009" intensity={1} decay={2} color="#ff4f24" position={[2.14, 1.706, -0.007]} rotation={[-1.279, 1.033, -Math.PI / 2]} scale={[0.183, 0.564, 0.148]} />
          <pointLight name="Area010" intensity={1} decay={2} color="#ff0011" position={[2.155, 1.5, 0.678]} rotation={[-1.279, 1.033, -Math.PI / 2]} scale={[0.183, 0.564, 0.148]} />
          <mesh name="Text-IK75001" geometry={nodes['Text-IK75001'].geometry} material={materials['2.001']} position={[0.376, 1.81, -2.413]} rotation={[Math.PI / 2, 0, 0.157]} scale={0.01} />
          <mesh name="Text-FEKER" geometry={nodes['Text-FEKER'].geometry} material={materials['2']} position={[0.376, 1.821, -2.413]} rotation={[Math.PI / 2, 0, 0.157]} scale={0.045} />
          <mesh name="Text-BORN" geometry={nodes['Text-BORN'].geometry} material={materials['4534595']} position={[0.644, 1.606, -2.274]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
          <mesh name="Plane137" geometry={nodes.Plane137.geometry} material={materials['Procedral White Silk']} position={[0.571, 1.795, -2.362]} rotation={[1.664, 0.015, 0.156]} scale={[0.003, 0.001, 0.003]} />
          <mesh name="bootle" geometry={nodes.bootle.geometry} material={materials['Raindrops On The Glass']} position={[1.634, 1.768, -2.411]} rotation={[0, -0.27, 0]} />
          <mesh name="wall" geometry={nodes.wall.geometry} material={materials['Fine leather white']} position={[0, -1.007, 0]} />
          <mesh name="floor" geometry={nodes.floor.geometry} material={materials['Wood.001']} position={[0, -1.007, 0]} />
          <mesh name="box05" geometry={nodes.box05.geometry} material={materials['Black Nickel']} position={[1.634, 1.768, -2.411]} rotation={[0, -0.27, 0]} />
          <mesh name="box03" geometry={nodes.box03.geometry} material={materials['White Stone']} position={[0, 1.809, -0.259]} />
          <mesh name="box01" geometry={nodes.box01.geometry} material={materials['Fine leather black']} position={[0.09, 0, 0.103]} />
          <mesh name="screen02" geometry={nodes.screen02.geometry} material={materials['Metal Black Dixon']} position={[0.396, 1.198, -0.891]} scale={[1.544, 0.167, 0.296]} />
          <mesh name="screen01" geometry={nodes.screen01.geometry} material={materials['Metal Black Dixon']} position={[0.396, 1.198, -0.252]} scale={[1.544, 0.167, 0.296]} />
          <mesh name="pad" geometry={nodes.pad.geometry} material={materials['Black and gold marble']} />
          <mesh name="chair" geometry={nodes.chair.geometry} material={materials['phongE2.002']} position={[0.843, 0, -0.671]} rotation={[0, Math.PI / 2, 0]} />
          <mesh name="Cube332" geometry={nodes.Cube332.geometry} material={materials['Black Nickel']} position={[1.996, 1.007, -2.164]} />
          <mesh name="Cube342" geometry={nodes.Cube342.geometry} material={materials['Black Nickel']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01" geometry={nodes['shelf-arm01'].geometry} material={materials['Material.006']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01001" geometry={nodes['shelf-arm01001'].geometry} material={materials['Material.001']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01002" geometry={nodes['shelf-arm01002'].geometry} material={materials['Material.002']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01003" geometry={nodes['shelf-arm01003'].geometry} material={materials['Material.003']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01004" geometry={nodes['shelf-arm01004'].geometry} material={materials['Material.004']} position={[0, -1.007, 0]} />
          <mesh name="shelf-arm01005" geometry={nodes['shelf-arm01005'].geometry} material={materials['Material.005']} position={[0, -1.007, 0]} />
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Black Nickel']} />
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Styrofoam with Black particles']} position={[0.992, 1.766, -0.153]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
